version: '3.7'

services:
  minio1:
    image: minio:v23.03
    hostname: minio1
    volumes:
      - /mnt/data/disk1:/disk1
      - /mnt/data/disk2:/disk2
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
    command: ["minio", "server", "http://minio{1...4}/disk{1...2}", "--console-address", ":9090"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 10

  minio2:
    image:  minio:v23.03
    hostname: minio2
    volumes:
      - /mnt/data/disk1:/disk1
      - /mnt/data/disk2:/disk2
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
    command: ["minio", "server", "http://minio{1...4}/disk{1...2}", "--console-address", ":9090"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 10

  minio3:
    image:  minio:v23.03
    hostname: minio3
    volumes:
      - /mnt/data/disk1:/disk1
      - /mnt/data/disk2:/disk2
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
    command: ["minio", "server", "http://minio{1...4}/disk{1...2}", "--console-address", ":9090"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 10

  minio4:
    image:  minio:v23.03
    hostname: minio4
    volumes:
      - /mnt/data/disk1:/disk1
      - /mnt/data/disk2:/disk2
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
    command: ["minio", "server", "http://minio{1...4}/disk{1...2}", "--console-address", ":9090"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 10s
      retries: 10
  
  minio-proxy:
    image: nginx:latest
    hostname: minio-proxy
    ports: 
      # - target: 9000
      #   published: 9000
      #   mode: host
      - target: 9090
        published: 9090
        mode: host
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    deploy:
      # mode: global
      replicas: 2
      placement:
        constraints: 
          - node.role==manager
    networks:
        - milvus-cluster-net

  etcd1:
    image: etcd:v3.5.5
    hostname: etcd1
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/data/etcd:/var/etcd
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.etcd1==true
    command: "etcd --name=infra1 --data-dir=/var/etcd/data.etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://etcd1:2379 --listen-peer-urls=http://0.0.0.0:2380 --initial-advertise-peer-urls=http://etcd1:2380 --initial-cluster-token=etcd-cluster --initial-cluster=infra1=http://etcd1:2380,infra2=http://etcd2:2380,infra3=http://etcd3:2380 --initial-cluster-state new"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  etcd2:
    image: etcd:v3.5.5
    hostname: etcd2
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/data/etcd:/var/etcd
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.etcd2==true
    command: "etcd --name=infra2 --data-dir=/var/etcd/data.etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://etcd2:2379 --listen-peer-urls=http://0.0.0.0:2380 --initial-advertise-peer-urls=http://etcd2:2380 --initial-cluster-token=etcd-cluster --initial-cluster=infra1=http://etcd1:2380,infra2=http://etcd2:2380,infra3=http://etcd3:2380 --initial-cluster-state new"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  etcd3:
    image: etcd:v3.5.5
    hostname: etcd3
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - /mnt/data/etcd:/var/etcd
    networks:
      - milvus-cluster-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.etcd3==true
    command: "etcd --name=infra3 --data-dir=/var/etcd/data.etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://etcd3:2379 --listen-peer-urls=http://0.0.0.0:2380 --initial-advertise-peer-urls=http://etcd3:2380 --initial-cluster-token=etcd-cluster --initial-cluster=infra1=http://etcd1:2380,infra2=http://etcd2:2380,infra3=http://etcd3:2380 --initial-cluster-state new"
    # healthcheck:
      # test: ["CMD", "curl", "-f", "http://localhost:2379/health"]
      # interval: 10s
      # timeout: 10s
      # retries: 10
  
  etcd-proxy:
    image: etcd:v3.5.5
    hostname: etcd-proxy
    ports: 
      - target: 23790
        published: 2379
        mode: host
    # volumes: 
    #   - proxy-data:/mnt/proxy
    # --data-dir=/mnt/proxy/proxy.etcd
    command: "etcd grpc-proxy start  --endpoints=http://etcd1:2379,http://etcd2:2379,http://etcd3:2379 --listen-addr=0.0.0.0:23790 --advertise-client-url=etcd-proxy:23790 --metrics-addr=http://0.0.0.0:8080"

    depends_on:
      - etcd1
      - etcd2
      - etcd3
    deploy:
      replicas: 2
      placement:
        constraints: 
          - node.role==manager
    networks:
        - milvus-cluster-net

networks:
  milvus-cluster-net:
    driver: overlay